server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  server:
    enable-self-preservation: false
    response-cache-update-interval-ms: 1000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
