server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 5
  client:
    fetch-registry: false
    register-with-eureka: false
