server:
  port: 9001
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/licensing_service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/user
