spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_in_action?useSSL=false&serverTimezone=UTC
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
