tracer:
  property: I AM THE DEFAULT
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_in_action
    username: user
    password: user
