eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_in_action?useSSL=false&serverTimezone=UTC
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: none
