server:
  port: 8000
zuul:
  ignoredServices: '*'
  routes:
    organisations:
      path: /organisations-service/**
      serviceId: organisations-service
    licensing:
      path: /licensing-service/**
      serviceId: licensing-service
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
